# Final models

Fit the final forecasting models and compare each one with persistence and AR(1) on the training and test sets.

In [13]:
import pandas as pd
import numpy as np

from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.compose import TransformedTargetRegressor
from sklearn.linear_model import ElasticNet, HuberRegressor, Lasso, LinearRegression, Ridge
from sklearn.metrics import root_mean_squared_error
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import SplineTransformer, StandardScaler

## Data preparation

In [14]:
train_data = (
    pd.read_parquet("../data/train.parquet")
    .sort_values("date")
    .reset_index(drop=True)
)
test_data = (
    pd.read_parquet("../data/test.parquet")
    .sort_values("date")
    .reset_index(drop=True)
)

for data in (train_data, test_data):
    data["usd_zar_28_movement"] = data["usd_zar_28"] - data["usd_zar"]

# Engineer train and test together so the first test rows can use training history
# for lagged and rolling features.
all_data = pd.concat(
    [train_data.assign(_split="train"), test_data.assign(_split="test")],
    ignore_index=True,
).sort_values("date").reset_index(drop=True)

all_data["interest_rate_diff"] = all_data["sa_repo_rate"] - all_data["us_fed_funds"]
all_data["policy_rate_differential"] = all_data["interest_rate_diff"]
all_data["sa_us_5y_yield_spread"] = all_data["sa_5y_yield"] - all_data["us_5y_yield"]

log_usd_zar = np.log(all_data["usd_zar"])
all_data["fx_log_return_5d"] = log_usd_zar.diff(5)
all_data["fx_log_return_21d"] = log_usd_zar.diff(21)
all_data["fx_realized_vol_21d"] = log_usd_zar.diff().shift(1).rolling(21).std()
all_data["fx_realized_vol_63d"] = log_usd_zar.diff().shift(1).rolling(63).std()
all_data["sa_cpi_log_change_21d"] = np.log(all_data["sa_cpi"]).diff(21)
all_data["sa_real_gdp_log_change_63d"] = np.log(all_data["sa_real_gdp"]).diff(63)
all_data["commodities"] = all_data[
    [
        "iron_ore_usd_per_tonne",
        "gold_usd_per_oz",
        "platinum_usd_per_oz",
        "richards_bay_coal_usd",
    ]
].mean(axis=1)

engineered_train = all_data.loc[all_data["_split"].eq("train")].drop(columns="_split").reset_index(drop=True)
engineered_test = all_data.loc[all_data["_split"].eq("test")].drop(columns="_split").reset_index(drop=True)

y_train = engineered_train["usd_zar_28_movement"]
y_test = engineered_test["usd_zar_28_movement"]

## AR(1) benchmark

In [15]:
AR1_HORIZON = 28

# Fit log(USD/ZAR)_t = intercept + phi * log(USD/ZAR)_(t-1)
# using training observations only.
train_log_usd_zar = np.log(engineered_train["usd_zar"])
ar1_model = LinearRegression()
ar1_model.fit(
    train_log_usd_zar.shift(1).iloc[1:].to_frame("lagged_log_usd_zar"),
    train_log_usd_zar.iloc[1:],
)


def ar1_movement_forecast(spot, horizon=AR1_HORIZON):
    """Return the AR(1) forecast as movement from the current spot level."""
    phi = float(ar1_model.coef_[0])
    intercept = float(ar1_model.intercept_)
    log_spot = np.log(np.asarray(spot))
    if np.isclose(phi, 1.0):
        log_forecast = log_spot + intercept * horizon
    else:
        log_forecast = phi**horizon * log_spot + intercept * (1 - phi**horizon) / (1 - phi)
    return np.exp(log_forecast) - np.asarray(spot)


def evaluate_model(model_name, model, features, data, target):
    """Compare movement RMSE for a fitted model, persistence, and AR(1)."""
    valid_rows = data[features].notna().all(axis=1) & target.notna()
    actual = target.loc[valid_rows]
    model_prediction = model.predict(data.loc[valid_rows, features])
    persistence_prediction = np.zeros(len(actual))
    ar1_prediction = ar1_movement_forecast(data.loc[valid_rows, "usd_zar"])

    return pd.DataFrame(
        {
            "RMSE": [
                root_mean_squared_error(actual, model_prediction),
                root_mean_squared_error(actual, persistence_prediction),
                root_mean_squared_error(actual, ar1_prediction),
            ]
        },
        index=[model_name, "Persistence", "AR(1)"],
    ).sort_values("RMSE")

## LightGBM

In [16]:
lgbm_features = [
    "gold_usd_per_oz",
    "usd_zar_1w_return",
    "usd_zar_1m_volatility",
    "interest_rate_diff",
]

lgbm_model = LGBMRegressor(
    n_estimators=150,
    learning_rate=0.05,
    num_leaves=15,
    random_state=42,
    verbosity=-1,
    n_jobs=1,
)
lgbm_model.fit(engineered_train[lgbm_features], y_train)

LGBMRegressor(learning_rate=0.05, n_estimators=150, n_jobs=1, num_leaves=15,
              random_state=42, verbosity=-1)

In [17]:
# Training data: LightGBM vs persistence and AR(1)
evaluate_model("LightGBM", lgbm_model, lgbm_features, engineered_train, y_train)

                 RMSE
LightGBM     0.306231
AR(1)        0.521657
Persistence  0.524441

In [18]:
# Test data: LightGBM vs persistence and AR(1)
evaluate_model("LightGBM", lgbm_model, lgbm_features, engineered_test, y_test)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
LightGBM     0.672096

## XGBoost

In [19]:
xgb_features = lgbm_features

xgb_model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=500,
    learning_rate=0.03,
    max_depth=3,
    min_child_weight=5,
    gamma=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.5,
    reg_lambda=2.0,
    random_state=42,
    n_jobs=-1,
)
xgb_model.fit(engineered_train[xgb_features], y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [20]:
# Training data: XGBoost vs persistence and AR(1)
evaluate_model("XGBoost", xgb_model, xgb_features, engineered_train, y_train)

                 RMSE
XGBoost      0.338730
AR(1)        0.521657
Persistence  0.524441

In [21]:
# Test data: XGBoost vs persistence and AR(1)
evaluate_model("XGBoost", xgb_model, xgb_features, engineered_test, y_test)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
XGBoost      0.661908

## Lasso

In [22]:
lasso_features = [
    "usd_zar",
    "brent_usd_per_barrel",
    "interest_rate_diff",
    "sa_us_5y_yield_spread",
    "sa_yoy_inflation",
    "sa_5y_cds_bp",
    "vix",
    "broad_usd_index",
    "sa_cpi",
    "usd_zar_1w_return",
    "usd_zar_1m_return",
    "usd_zar_3m_return",
    "usd_zar_1m_volatility",
]

lasso_model = make_pipeline(
    StandardScaler(),
    Lasso(alpha=0.1, max_iter=50_000),
)
lasso_model.fit(engineered_train[lasso_features], y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('lasso', Lasso(alpha=0.1, max_iter=50000))])

In [23]:
# Training data: Lasso vs persistence and AR(1)
evaluate_model("Lasso", lasso_model, lasso_features, engineered_train, y_train)

                 RMSE
AR(1)        0.521657
Lasso        0.522753
Persistence  0.524441

In [24]:
# Test data: Lasso vs persistence and AR(1)
evaluate_model("Lasso", lasso_model, lasso_features, engineered_test, y_test)

                 RMSE
Lasso        0.544020
AR(1)        0.544117
Persistence  0.544335

## Multi-Layer Perceptron

In [25]:
mlp_features = [
    "gold_usd_per_oz_return",
    "sa_yoy_inflation",
    "usd_zar_1m_return",
    "usd_zar_1m_volatility",
]

mlp_model = make_pipeline(
    StandardScaler(),
    MLPRegressor(
        hidden_layer_sizes=(128, 64, 32),
        alpha=0.01,
        learning_rate="adaptive",
        max_iter=1000,
        early_stopping=True,
        validation_fraction=0.15,
        n_iter_no_change=30,
        random_state=42,
    ),
)
mlp_model.fit(engineered_train[mlp_features], y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('mlpregressor',
                 MLPRegressor(alpha=0.01, early_stopping=True,
                              hidden_layer_sizes=(128, 64, 32),
                              learning_rate='adaptive', max_iter=1000,
                              n_iter_no_change=30, random_state=42,
                              validation_fraction=0.15))])

In [26]:
# Training data: MLP vs persistence and AR(1)
evaluate_model("MLP", mlp_model, mlp_features, engineered_train, y_train)

                 RMSE
MLP          0.378550
AR(1)        0.521657
Persistence  0.524441

In [27]:
# Test data: MLP vs persistence and AR(1)
evaluate_model("MLP", mlp_model, mlp_features, engineered_test, y_test)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
MLP          0.652374

## OLS

In [28]:
ols_features = [
    "broad_usd_index",
    "brent_usd_per_barrel",
    "sa_cpi",
    "usd_zar_1m_return",
    "fx_log_return_5d",
    "fx_log_return_21d",
    "sa_cpi_log_change_21d",
    "sa_real_gdp_log_change_63d",
]

ols_model = make_pipeline(StandardScaler(), LinearRegression())
ols_rows = engineered_train[ols_features].notna().all(axis=1)
ols_model.fit(engineered_train.loc[ols_rows, ols_features], y_train.loc[ols_rows])

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [29]:
# Training data: OLS vs persistence and AR(1)
evaluate_model("OLS", ols_model, ols_features, engineered_train, y_train)

                 RMSE
OLS          0.511429
AR(1)        0.520429
Persistence  0.523316

In [30]:
# Test data: OLS vs persistence and AR(1)
evaluate_model("OLS", ols_model, ols_features, engineered_test, y_test)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
OLS          0.614477

## Ridge

In [31]:
ridge_features = [
    "sa_repo_rate",
    "sa_real_gdp",
    "policy_rate_differential",
    "sa_us_5y_yield_spread",
    "sa_cpi_log_change_21d",
]

ridge_model = make_pipeline(StandardScaler(), Ridge(alpha=10.0))
ridge_rows = engineered_train[ridge_features].notna().all(axis=1)
ridge_model.fit(engineered_train.loc[ridge_rows, ridge_features], y_train.loc[ridge_rows])

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('ridge', Ridge(alpha=10.0))])

In [32]:
# Training data: Ridge vs persistence and AR(1)
evaluate_model("Ridge", ridge_model, ridge_features, engineered_train, y_train)

                 RMSE
Ridge        0.506723
AR(1)        0.521128
Persistence  0.523839

In [33]:
# Test data: Ridge vs persistence and AR(1)
evaluate_model("Ridge", ridge_model, ridge_features, engineered_test, y_test)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
Ridge        0.548637

## Elastic Net

In [34]:
elastic_net_features = [
    "sa_real_gdp",
    "sa_5y_cds_bp",
    "sa_5y_yield",
    "policy_rate_differential",
    "fx_log_return_5d",
    "fx_realized_vol_21d",
]

elastic_net_model = TransformedTargetRegressor(
    regressor=make_pipeline(
        StandardScaler(),
        ElasticNet(alpha=0.02, l1_ratio=0.35, max_iter=20_000, random_state=42),
    ),
    transformer=StandardScaler(),
)
elastic_net_rows = engineered_train[elastic_net_features].notna().all(axis=1)
elastic_net_model.fit(
    engineered_train.loc[elastic_net_rows, elastic_net_features],
    y_train.loc[elastic_net_rows],
)

TransformedTargetRegressor(regressor=Pipeline(steps=[('standardscaler',
                                                      StandardScaler()),
                                                     ('elasticnet',
                                                      ElasticNet(alpha=0.02,
                                                                 l1_ratio=0.35,
                                                                 max_iter=20000,
                                                                 random_state=42))]),
                           transformer=StandardScaler())

In [35]:
# Training data: Elastic Net vs persistence and AR(1)
evaluate_model(
    "Elastic Net",
    elastic_net_model,
    elastic_net_features,
    engineered_train,
    y_train,
)

                 RMSE
Elastic Net  0.496397
AR(1)        0.521203
Persistence  0.523910

In [36]:
# Test data: Elastic Net vs persistence and AR(1)
evaluate_model(
    "Elastic Net",
    elastic_net_model,
    elastic_net_features,
    engineered_test,
    y_test,
)

                 RMSE
AR(1)        0.544117
Persistence  0.544335
Elastic Net  0.554314

## Huber

In [37]:
huber_features = [
    "sa_repo_rate",
    "usd_zar_1m_return",
    "sa_cpi_log_change_21d",
]

huber_model = TransformedTargetRegressor(
    regressor=make_pipeline(
        StandardScaler(),
        HuberRegressor(epsilon=1.35, alpha=0.01, max_iter=2_000),
    ),
    transformer=StandardScaler(),
)
huber_rows = engineered_train[huber_features].notna().all(axis=1)
huber_model.fit(
    engineered_train.loc[huber_rows, huber_features],
    y_train.loc[huber_rows],
)

TransformedTargetRegressor(regressor=Pipeline(steps=[('standardscaler',
                                                      StandardScaler()),
                                                     ('huberregressor',
                                                      HuberRegressor(alpha=0.01,
                                                                     max_iter=2000))]),
                           transformer=StandardScaler())

In [38]:
# Training data: Huber vs persistence and AR(1)
evaluate_model("Huber", huber_model, huber_features, engineered_train, y_train)

                 RMSE
AR(1)        0.521128
Huber        0.523688
Persistence  0.523839

In [39]:
# Test data: Huber vs persistence and AR(1)
evaluate_model("Huber", huber_model, huber_features, engineered_test, y_test)

                 RMSE
Huber        0.540929
AR(1)        0.544117
Persistence  0.544335

## Spline Ridge

In [40]:
spline_ridge_features = [
    "iron_ore_usd_per_tonne",
    "sa_repo_rate",
    "sa_cpi",
    "sa_yoy_inflation",
    "usd_zar_1w_return",
    "usd_zar_1m_return",
    "sa_5y_yield",
    "interest_rate_diff",
    "fx_realized_vol_63d",
]

spline_ridge_model = make_pipeline(
    StandardScaler(),
    SplineTransformer(n_knots=4, degree=2, include_bias=False),
    Ridge(alpha=25.0),
)
spline_ridge_rows = engineered_train[spline_ridge_features].notna().all(axis=1)
spline_ridge_model.fit(
    engineered_train.loc[spline_ridge_rows, spline_ridge_features],
    y_train.loc[spline_ridge_rows],
)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('splinetransformer',
                 SplineTransformer(degree=2, include_bias=False, n_knots=4)),
                ('ridge', Ridge(alpha=25.0))])

In [41]:
# Training data: Spline Ridge vs persistence and AR(1)
evaluate_model(
    "Spline Ridge",
    spline_ridge_model,
    spline_ridge_features,
    engineered_train,
    y_train,
)

                  RMSE
Spline Ridge  0.477664
AR(1)         0.520351
Persistence   0.523211

In [42]:
# Test data: Spline Ridge vs persistence and AR(1)
evaluate_model(
    "Spline Ridge",
    spline_ridge_model,
    spline_ridge_features,
    engineered_test,
    y_test,
)

                  RMSE
AR(1)         0.544117
Persistence   0.544335
Spline Ridge  0.562254